# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Blog"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: "Blog about web development."

# Tagline below the site title
tagline: "web development"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "renangabriel27.github.io/blog"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /blog
- text: Archives
  url: /blog/tags/
- text: Web development
  url: /blog/webdev

# The shortname for your Disqus site to enable comments.
disqus: renangabriel-github-io

# Author information - author info at the bottom of the post
author_name: "Renan Gabriel"
author_bio: "Hello, I'm Renan Gabriel, Brazilian and Web Development Student."
author_url: ""
author_location: "Brazil"
author_image: authorimage.jpg

# Footer ad banner
banner_url: ""
banner_image: banner.jpg

# Footer newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: ""

# Social links in the site footer
facebook_username: "renangabriel27"
github_username: "renangabriel27"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
